CREATE TABLE player_data
  (
    gameid varchar(150),
    team varchar(5),
    opponent varchar(5),
    position varchar(5),
    player varchar(50),
    X3FGA int,
    X3FGM int,
    FGA int,
    FGM int,
    FTA int,
    FTM int,
    assists int,
    blocks int,
    fouls int,
    minutes int,
    points int,
    off_rebounds int,
    def_rebounds int,
    steals int,
    turnovers int,
    starter int,
    date date,
    PRIMARY KEY (gameid,player,team)
  );

CREATE TABLE event_data
  (
    gameid varchar(150),
    home_team varchar(5),
    away_team varchar(5),
    attendance int,
    official_1 varchar(50),
    official_2 varchar(50),
    official_3 varchar(50),
    official_4 varchar(50),
    season_type varchar(25),
    home_score int,
    away_score int,
    duration int, --convert string '2:25' to minutes!!
    away_3FGA int,
    away_3FGM int,
    away_FGA int,
    away_FGM int,
    away_FTA int,
    away_FTM int,
    away_assists int,
    away_blocks int,
    away_fouls int,
    away_off_rebounds int,
    away_def_rebounds int,
    away_steals int,
    away_turnovers int,
    away_Q1 int,
    away_Q2 int,
    away_Q3 int,
    away_Q4 int,
    away_Q5 int,
    away_Q6 int,
    away_Q7 int,
    away_Q8 int,
    home_3FGA int,
    home_3FGM int,
    home_FGA int,
    home_FGM int,
    home_FTA int,
    home_FTM int,
    home_assists int,
    home_blocks int,
    home_fouls int,
    home_off_rebounds int,
    home_def_rebounds int,
    home_steals int,
    home_turnovers int,
    home_Q1 int,
    home_Q2 int,
    home_Q3 int,
    home_Q4 int,
    home_Q5 int,
    home_Q6 int,
    home_Q7 int,
    home_Q8 int,
    date date,
    time timestamp,
    PRIMARY KEY (gameid)
  );
